import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AppContextProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          <div className="min-h-screen flex flex-col justify-between">
            <Navbar />
            <div>
              {children}
            </div>
            <div className="w-full mx-auto py-8 bg-gray-400 ">
              <p className="max-w-7xl text-center text-3xl text-black bg-amber-100 mx-auto">Add a Footer</p>
            </div>

          </div>
        </AppContextProvider>

      </body>
    </html>
  );
}
